name: feature_request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: logic-rationale
    attributes:
      label: Rationale
      description: Why is this feature needed?
    validations:
      required: true
